"""Add deleted at column to languages

Revision ID: 4a09bdedf6c3
Revises: 0fa7bfc09aae
Create Date: 2024-01-01 21:17:42.695160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a09bdedf6c3'
down_revision: Union[str, None] = '0fa7bfc09aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_decks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('languages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'deleted_at')
    op.drop_column('card_decks', 'deleted_at')
    # ### end Alembic commands ###
