"""Migration to add grammar info field

Revision ID: 52794bd02ed4
Revises: 0f8384d82b5b
Create Date: 2024-01-16 19:36:26.073002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52794bd02ed4'
down_revision: Union[str, None] = '0f8384d82b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flash_cards', sa.Column('grammar_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flash_cards', 'grammar_info')
    # ### end Alembic commands ###
