"""Add type to study run

Revision ID: d36cbd7343e7
Revises: 52794bd02ed4
Create Date: 2024-03-01 20:23:51.071322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36cbd7343e7'
down_revision: Union[str, None] = '52794bd02ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    types = sa.Enum('from_target', 'to_target', name='studytype')
    types.create(op.get_bind())
    op.add_column(
        'study_runs',
        sa.Column('run_type', types, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_runs', 'run_type')
    types = sa.Enum('from_target', 'to_target', name='studytype')
    types.drop(op.get_bind())
    # ### end Alembic commands ###
